### PR TITLE
avoid that 11_exoGAINS overwrites fulldata.gdx, improve restart message

### PR DESCRIPTION
**Pull request by orichters**
## Purpose of this PR
- Fixes two issues with 11_exoGAINS: first, that it overwrites `fulldata.gdx` in the middle of an iteration, causing some mess on restarts sometimes. #918. Second, that after non-optimal solve in early iterations, no fulldata.gdx is found and it crashes. Solution is to write an own gdx file that is only used by exoGAINS and later deleted
- improve some logging, preserve `log.txt` as `log_beforeRestart.txt` if runs are restarted and tell the user about it

## Type of change

- [x] Bug fix 
- [x] No change in scenario results

## Checklist:

- [x] My code follows the coding etiquette
- [x] I have performed a self-review of my own code
- [x] The model compiles and runs successfully (see `/p/tmp/oliverr/remind/output/default_2022-10-06_17.35.04`)

### CODE REVIEW

**Comment by merfort** [comment]
Thanks Oli! 
Regarding the problem that overwriting `fulldata.gdx` this fix should work.

I am just a bit confused regarding the part of the missing `fulldata.gdx` in case of an early non-optimal solve. As far as I understand it, the way it **worked before** was, that REMIND writes `non_optimal.gdx` in case of a non-optimal solution and `exoGAINSAirpollutants.R` in that case falls back to `input.gdx` instead (if there is no `fulldata.gdx` from a previous iteration). So the problem is not that no `fulldata.gdx` was found, but rather that there actually is a `fulldata.gdx` that somehow contains some values that break the reporting, probably due to the fact that the iteration was non-optimal. At least in my case (`/p/tmp/merfort/REMIND_development/remind/output/SSP2EU-PkBudg500_sustTax_1p5_EFTtax_20_glob_v2_2022-10-13_17.47.17`) the problem is that using `fulldata.gdx` breaks the reporting within `exoGAINSAirpollutants.R`, while using `input.gdx` would work (I checked that). I just don't know, why the `fulldata.gdx` that was written after the second iteration breaks the reporting, since the second iteration was actually feasible...

To cut a long story short, in theory the original implementation (only reporting when optimal) should work, and I would actually rather not write a `fulldata_exoGAINS.gdx` after a non-optimal solution, since this might actually break the reporting, while using `input.gdx` doesn't.
Or am I getting this completely wrong?

A minor point: I think it would be nice if exoGAINSAirpollutants.R wrote something like "No fulldata_exoGAINS.gdx found, using input.gdx instead" in that case, that would help with debugging in the future.

**Comment by merfort** [comment]
Btw, I pulled from your branch and reran my scenario, but the bug persists.

**Comment by orichters** [comment]
I have to admit, @merfort, then I don't understand the problem at all. Because exoGAINS was never run on a gdx file from an non_optimal iterations. Because if it did not converge, it was writing to `non_optimal.gdx` but always loading from `fulldata.gdx` or `input.gdx`. So I don't know at all why your runs fail.

**Comment by merfort** [comment]
Ok, I did some further tests and I think, I can clarify this. There are two unrelated issues:
1) The problem with my runs is not related to the missing of a `fulldata.gdx`. The cause here is most likely that I used some (too) old NDC runs as reference (for pre-2025 values), which somehow breaks the reporting. It just already emerges at REMIND runtime, because `exoGAINSAirpollutants.R` calls some reporting functions (in particular `reportFE`). That is a bit inconvenient, since you usually don't want a broken reporting to also break REMIND itself, but I would not know, how to prevent that, since `exoGAINSAirpollutants.R` apparently relies on some reporting variables. Sorry for the confusion that I introduced with my runs!
2) With your updates in `modules/11_aerosols/exoGAINS/postsolve.gms` REMIND will now always write a gdx file that can be used for `exoGAINSAirpollutants.R` , also in the case of a non-optimal solution. I think that may potentially lead to errors within the reporting functions called within `exoGAINSAirpollutants.R`. So, my suggestion would be to write `fulldata_exoGAINS.gdx` only in the case of an optimal solution, i.e. keep the condition `if((o_modelstat le 2), ...`. Consequently REMIND will fallback to `input.gdx` if it there are non-optimal solutions in the first iteration(s) and to the last successfully written `fulldata_exoGAINS.gdx` in case of non-optimal solutions in later iterations.

**Review by merfort — APPROVED** [review]
Thanks! Looks all good now.

**Pull request merged**
