### PR TITLE
only solve regions that do not have a valid solution for this nash iteration

### PR DESCRIPTION
**Pull request by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q**
If one or more regions fail to solve, not all regions are passed to
CONOPT again, potentially speeding up model runtimes (especially for 
EU21) and allowing for higher values of cm_solver_try_max, as truely
infeasible regions will return from CONOPT rather fast.

Also, `resusd` in `p80_repy_iteration` now shows total time used for all `sol_itr`, not only the last.

## Type of change
- [x] New feature 

## Checklist:

- [x] My code follows the [coding etiquette](https://github.com/remindmodel/remind/blob/develop/main.gms#L80)
- [ ] I performed a self-review of my own code
- [x] I explained my changes within the PR, particularly in hard-to-understand areas
- [x] I checked that the [in-code documentation](https://github.com/remindmodel/remind/blob/develop/maxn.gms#L120) is up-to-date
- [x] I adjusted the reporting in [`remind2`](https://github.com/pik-piam/remind2) where it was needed
- [x] I adjusted `forbiddenColumnNames` in [readCheckScenarioConfig.R](https://github.com/remindmodel/remind/blob/develop/scripts/start/readCheckScenarioConfig.R) in case the PR leads to deprecated switches
- [x] All automated model tests pass (`FAIL 0` in the output of `make test`)
- [x] The changelog `CHANGELOG.md` [has been updated correctly](https://gitlab.pik-potsdam.de/rse/rsewiki/-/wikis/Standards-for-Writing-a-Changelog)

### CODE REVIEW

**Comment by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q** [comment]
@Renato-Rodrigues, relevant changes are only in [this commit](https://github.com/remindmodel/remind/pull/1522/commits/ed0d54cee065fad922106196cb60d63be580c186?diff=unified&w=1), the rest is cleaning files.

**Review by Renato-Rodrigues — APPROVED** [review]
It looks like a great improvement.
Thank you for implementing this!

Just an additional suggestion, maybe we could also store in `p80_repy_iteration` the number of `sol_itr` tried for each region at each iteration as this will vary now depending of the solver capacity to find a solution.

**Comment by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q** [comment]
> Just an additional suggestion, maybe we could also store in `p80_repy_iteration` the number of `sol_itr` tried for each region at each iteration as this will vary now depending of the solver capacity to find a solution.

Not in `p80_repy_iteration`, unless we modify `solveinfo80`, which would break call kinds of stuff.

But have you met ~~Ted~~[`p80_repy_nashitr_solitr`](https://github.com/remindmodel/remind/pull/1522/files#diff-afcf543d3c9525ea477e1750ff605c34ad4b854da9f7c01aa06431b321a412a7R116)?

**Comment by Renato-Rodrigues** [comment]
> Not in `p80_repy_iteration`, unless we modify `solveinfo80`, which would break call kinds of stuff.
> 
> But have you met ~Ted~[`p80_repy_nashitr_solitr`](https://github.com/remindmodel/remind/pull/1522/files#diff-afcf543d3c9525ea477e1750ff605c34ad4b854da9f7c01aa06431b321a412a7R116)?

👍 :)

I must have being blind to have missed "Ted".

**Comment by robertpietzcker** [comment]
thanks also from my side, Michaja - a great improvement!!

**Comment by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q** [comment]
> the messaging why an iteration did not converge now displays "infeasible" even if the region got feasible in the repeated iteration

What messaging?

**Comment by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q** [comment]
Wow, that's some arcane REMIND stuff … and a terrible user interface.

The reason is because `p80_repy` [gets reset to 0](https://github.com/remindmodel/remind/blob/b7f385bb5c00b504f3cad6a82a16ce0ef283814b/modules/80_optimization/nash/solve.gms#L20-L26)
```
  if (    sol_itr.val gt 1
      AND (   p80_repy(all_regi,"modelstat") eq 2
           OR p80_repy(all_regi,"modelstat") eq 7),


    p80_repy(all_regi,solveinfo80) = 0;
    continue;
  );
```
for the regions that do not need another CONOPT iteration (everything besides `JPN` in your example), so that they can be excluded from `p80_repy_iteration` and `p80_repy_nashitr_solitr` [later on](https://github.com/remindmodel/remind/blob/b7f385bb5c00b504f3cad6a82a16ce0ef283814b/modules/80_optimization/nash/solve.gms#L108-L118)
```
p80_repy_iteration(all_regi,solveinfo80,iteration)$(
                                                p80_repy(all_regi,solveinfo80) )
    !! store sum of resusd for all sol_itrs
  = ( p80_repy_iteration(all_regi,solveinfo80,iteration)
    + p80_repy(all_regi,solveinfo80)
    )$( sameas(solveinfo80,"resusd") )
  + p80_repy(all_regi,solveinfo80)$( NOT sameas(solveinfo80,"resusd") );


p80_repy_nashitr_solitr(all_regi,solveinfo80,iteration,sol_itr)$(
                                                p80_repy(all_regi,solveinfo80) )
  = p80_repy(all_regi,solveinfo80);
```
You could try this ([here](https://github.com/remindmodel/remind/blob/6bc0d045141a3a5af894b9925993b0845778f4d2/modules/80_optimization/nash/postsolve.gms#L281-L286))
```diff
 *** critertion "infes": and are all solutions optimal?
 loop(regi,
-     if((p80_repy(regi,'modelstat') ne 2) and (p80_repy(regi,'modelstat') ne 7),
+     if (    p80_repy(regi,"modelstat") ne 0 
+         AND p80_repy(regi,"modelstat") ne 2
+         AND p80_repy(regi,"modelstat") ne 7,
          s80_bool = 0;
          p80_messageShow("infes") = YES;
      );
```
which should fix it, `modelstat` [should never return 0](https://www.gams.com/44/docs/UG_GamsCall.html#GAMSAOmodelstat).

**Pull request merged**
