### PR TITLE
Add plotIterations and plotRuntime output scripts

### PR DESCRIPTION
**Pull request by pfuehrlich-pik**
- Adds the REMIND output scripts plotIterations (single) and plotRuntime (comparison), available via `Rscript output.R`.
- PlotIterations will create a customizable Rmd file which creates plots for given variables, plotting years on the x axis and the iteration number on an interactive plotly slider. The core functions used in that Rmd file are available in the mip package with this PR: https://github.com/pik-piam/mip/pull/21.
- The plotIterations script is largely based on a script by @rkrekeler. It is intended for runtime comparisons of different configurations, it does so by visualizing the runtime of selected runs via 4 different plots.
- The output.R and EDGETransportMultiIterationAnalysis.Rmd files are auto-formatted and some linter warnings fixed. (They don't need review I think.)
- @rkrekeler and @MariannaR your review and feedback is appreciated (cannot add you as reviewers, probably missing permission)

### CODE REVIEW

**Comment by giannou** [comment]
now you should be able to assign reviewers

**Comment by pfuehrlich-pik** [comment]
I can add Marianna as reviewer, but not Robin. Maybe he needs to be in the remindmodel organization as well?

**Comment by pfuehrlich-pik** [comment]
Here's a sample Rmd file created by plotIterations (had to rename to txt because of GitHub) [plotIterations_2021-07-12_11:29:07.txt](https://github.com/remindmodel/remind/files/6800258/plotIterations_2021-07-12_11.29.07.txt).
And here's how the plots look like initially (lacking some color, but that can easily be added in the Rmd) 
Screenshot from 2021-07-12 11-33-33

**Comment by pfuehrlich-pik** [comment]
Here an example of the 4 plots created by plotRuntime
Screenshot from 2021-07-12 11-42-39
Screenshot from 2021-07-12 11-50-53
Screenshot from 2021-07-12 11-51-05

**Comment by giannou** [comment]
> I can add Marianna as reviewer, but not Robin. Maybe he needs to be in the remindmodel organization as well?

as soon as he accepts the invitation to be a member of the repo you will be able to add him as reviewer

**Review by MariannaR — APPROVED** [review]

**Pull request merged**
