### PR TITLE
set SSP2EU as default GDP and population scenario

### PR DESCRIPTION
**Pull request by LaviniaBaumstark**

### CODE REVIEW

**Comment by giannou** [comment]
Do we need to adjust also the `scenario_config_XXX.csv` files?

**Comment by LaviniaBaumstark** [comment]
I will adjust the scenario_config for the validation. All others need to take this decision project based. Anyway, we need to clean up the number of scenario_configs in the config-folder

**Comment by giannou** [comment]
what about the scenario_config_AMT.csv?

**Comment by LaviniaBaumstark** [comment]
We could change them now, but also later

**Review by giannou — APPROVED** [review]

**Pull request merged**
