### PR TITLE
Update ScenarioMIP config files in line with internal protocol v4

### PR DESCRIPTION
**Pull request by laurinks**
## Purpose of this PR

Update ScenarioMIP config files (REMIND standalone and coupling) according to [Internal scenario protocol (v4) - ScenarioMIP main phase](https://docs.google.com/document/d/1rAHpkkYHKIDsoIZOqfqLbHMJlTzvYtPg5RhIGHSlkyc/edit?usp=sharing)

## Type of change

- [x] Update of non-default config files

## Checklist:

- [x] My code follows the [coding etiquette](https://github.com/remindmodel/remind/blob/develop/main.gms#L80)
- [x] I performed a self-review of my own code
- [x] I explained my changes within the PR, particularly in hard-to-understand areas
- [x] I checked that the [in-code documentation](https://github.com/remindmodel/remind/blob/develop/main.gms#L120) is up-to-date
- [ ] I adjusted the reporting in [`remind2`](https://github.com/pik-piam/remind2) where it was needed
- [x] I adjusted `forbiddenColumnNames` in [readCheckScenarioConfig.R](https://github.com/remindmodel/remind/blob/develop/scripts/start/readCheckScenarioConfig.R) in case the PR leads to deprecated switches
- [x] All automated model tests pass (`FAIL 0` in the output of `make test`)
- [x] The changelog `CHANGELOG.md` [has been updated correctly](https://gitlab.pik-potsdam.de/rse/rsewiki/-/wikis/Standards-for-Writing-a-Changelog)

### CODE REVIEW

**Comment by laurinks** [comment]
Comparison of default ScenarioMIP scenarios with default REMIND scenarios:

```
File comparison: /p/projects/rd3mod/github/repos/remindmodel/remind/develop/config/scenario_config.csv -> ./config/scenario_config_ScenarioMIP.csv
Columns deleted: c_ccscapratescen, c_tech_earlyreti_rate, capitalMarket, CES_parameters, cm_bioenergy_SustTax, cm_emiMktTarget, cm_prtpScen, extramappings_historic, regionmapping, slurmConfig
Columns added:   cm_maxProdBiolc, cm_taxCO2_historical, cm_taxCO2_historicalYr, cm_taxCO2_IncAfterPeakBudgYr, cm_taxCO2_interpolation, copyConfigFrom
Renamed columns: -
Renamed rows:    SSP2-NPi2025 -> SMIPv04-M-SSP2-NPi2025-def, SSP3-rollBack -> SMIPv04-H-SSP3-rollBack-def, SSP2-PkBudg1000 -> SMIPv04-L-SSP2-PkBudg1000-def, SSP2-EcBudg400 -> SMIPv04-VLHO-SSP2-EcBudg400-def, SSP1-PkBudg650 -> SMIPv04-VLLO-SSP1-PkBudg650-def

Changes in the scenarios:
~ SSP3-rollBack -> SMIPv04-H-SSP3-rollBack-def:
    cm_budgetCO2from2020: 0 -> 1150 (default: 1150)
    cm_33EW: 0 -> 1 (default: 0)
    path_gdx_ref: SSP2-NPi2025 -> SMIPv04-M-SSP2-NPi2025-def
    path_gdx_refpolicycost: SSP3-NPi2025 -> SMIPv04-M-SSP2-NPi2025-def
    description: was changed (default: REMIND run with default settings)
~ SSP2-NPi2025 -> SMIPv04-M-SSP2-NPi2025-def:
    start: 1,AMT,2 -> 1
    cm_budgetCO2from2020: 0 -> 1150 (default: 1150)
    cm_33EW: 0 -> 1 (default: 0)
    description: was changed (default: REMIND run with default settings)
+ SMIPv04-ML-SSP2-PkBudg1500-def was added.
~ SSP2-PkBudg1000 -> SMIPv04-L-SSP2-PkBudg1000-def:
    start: 1,AMT,2 -> 1
    cm_taxCO2_startyear: 75 -> 65 (default: -1)
    cm_taxCO2_regiDiff_endYr: "GLO 2050" -> GLO 2070 (default: "GLO 2050")
    cm_33EW: 0 -> 1 (default: 0)
    c_changeProdCost: 1 -> 5 (default: 5)
    path_gdx_ref: SSP2-NPi2025 -> SMIPv04-M-SSP2-NPi2025-def
    path_gdx_refpolicycost: SSP2-NPi2025 -> SMIPv04-M-SSP2-NPi2025-def
    description: was changed (default: REMIND run with default settings)
    cm_taxCO2_historical: NA -> 55 (default: gdx_ref)
    cm_taxCO2_historicalYr: NA -> 2028 (default: last)
    cm_taxCO2_IncAfterPeakBudgYr: NA -> 5 (default: 0)
~ SSP2-EcBudg400 -> SMIPv04-VLHO-SSP2-EcBudg400-def:
    start: 1,AMT,2 -> 1
    cm_implicitQttyTarget: (2080,2090,2100).GLO.tax.t.oae.all 5000 -> (2080,2090,2100,2110,2130,2150).GLO.tax.t.oae.all 5000 (default: off)
    path_gdx_ref: SSP2-NPi2025 -> SMIPv04-M-SSP2-NPi2025-def
    path_gdx_refpolicycost: SSP2-NPi2025 -> SMIPv04-M-SSP2-NPi2025-def
    description: was changed (default: REMIND run with default settings)
    cm_taxCO2_interpolation: NA -> one_step (default: off)
~ SSP1-PkBudg650 -> SMIPv04-VLLO-SSP1-PkBudg650-def:
    start: 1,AMT -> 1
    cm_taxCO2_startyear: 100 -> 75 (default: -1)
    cm_taxCO2_regiDiff_endYr: "GLO 2050" -> GLO 2050 (default: "GLO 2050")
    cm_33EW: 0 -> 1 (default: 0)
    c_ccsinjecratescen: 2 -> 5 (default: 1)
    cm_CESMkup_build: feelhpb 1.05, fehob 1.75, feheb 0.1 -> standard (default: standard)
    cm_CESMkup_ind: manual -> standard (default: standard)
    cm_CESMkup_ind_data: feh2_otherInd 1.04, feelhth_otherInd 0.4, feh2_cement 2.0, feelhth_chemicals 1.3, feh2_chemicals 1.04 -> "" (default: "")
    cm_tradecostBio: 0.5 -> 1 (default: 1)
    c_changeProdCost: 1 -> 5 (default: 5)
    path_gdx_ref: SSP2-NPi2025 -> SMIPv04-M-SSP2-NPi2025-def
    path_gdx_refpolicycost: SSP1-NPi2025 -> SMIPv04-M-SSP2-NPi2025-def
    description: was changed (default: REMIND run with default settings)
    cm_maxProdBiolc: NA -> 100 (default: off)
    cm_taxCO2_historical: NA -> 55 (default: gdx_ref)
    cm_taxCO2_historicalYr: NA -> 2028 (default: last)
```

**Comment by laurinks** [comment]
@dklein-pik : This fixes the problem in the coupling tests.
@flohump: Could you have a quick look at the coupled config to make sure everything is as intended on the MAgPIE side? Thanks!
@LaviniaBaumstark, @gunnar-pik, @robertpietzcker, @nicobauer: For your information, I added the comparison between REMIND default scenarios and REMIND settings for ScenarioMIP (see comment). As you see, for High and Medium, EW is the only difference. I am also keeping variants without EW in the config for comparison/back-up.

**Review by flohump — CHANGES_REQUESTED** [review]
Column `config/scenario_config.csv`
`|rcpXpX` is not needed and can be safely removed.
We don't use climate change impacts in the ScenarioMIP runs. This is set by `nocc_hist`. Setting an addtional `rcpXpX` impact pathway is confusing.

Column `no_ghgprices_land_until`
SMIPv04-VLHO-SSP2-EcBudg400-def has `y2035`. Why 2035 and not 2030? 

Everything else looks fine

**Comment by laurinks** [comment]
> Column `no_ghgprices_land_until`
SMIPv04-VLHO-SSP2-EcBudg400-def has y2035. Why 2035 and not 2030?

Because we fix the scenario to the Medium scenario in 2030. REMIND `cm_startyear` is consistently set to 2035. The ScenarioMIP paper asks for the VLHO scenario to follow current policies in 2030, and only deviate thereafter. Motivations: delayed climate policy + sufficient difference between VLLO and VLHO for signal in ESMs.

**Comment by laurinks** [comment]
Summary of exchange with @dklein-pik and @flohump : 
- `no_ghgprices_land_until = 20xx` means that GHG prices will be set to zero (in MAgPIE) until and including the year 20xx.
- Until 2030, climate policy in MAgPIE is implemented via NDC policies, thus `no_ghgprices_land_until` is always chosen to be 2030 or later. 

For coupling configs, this implies:
- All scenarios with REMIND `cm_startyear <= 2035` use `no_ghgprices_land_until = 2030`.
- All scenarios with REMIND` cm_startyear >= 2040` use `no_ghgprices_land_until = X`, with `X` being the timestep before `cm_startyear` ist. Example: `cm_startyear = 2045` --> `no_ghgprices_land_until = 2040`

**Review by flohump — APPROVED** [review]
scenario_config_coupled looks now fine from MAgPIE side

**Pull request merged**
