### PR TITLE
add constraint to have equal shares of synfuels in biofuel+synfuel total per transport subsectors

### PR DESCRIPTION
**Pull request by fschreyer**
After a recent discussion with Robert, we said we would for now want to have equal shares of synfuels and biofuels per transport subsector (LDV, HDV, Bunkers) as there seems to be no real reason why we should put all biofuels into bunkers and all synfuels into trucks or vice versa which REMIND does quite arbitrarily at the moment. 

So this constraint, makes the synfuel share in carbon-neutral liquids (biofuel+synfuels) the same in ``fepet`` (LDV), ``fedie.ES`` (HDV), and ``fedie.other`` (Bunkers). 

We are planning to soon add reporting of that fuel distinction in the EDGE-T reporting based on the shares in ``vm_demFeSector``.

### CODE REVIEW

**Comment by Renato-Rodrigues** [comment]
Why the shares are calculated on bio and synfuel only? Wouldn't you need to consider fossils also in the equation to enforce the same bio+syn on different modes?

Maybe I am missing something, but at a quick look you are enforcing the share of synfuels in bio+syn to be the same, but you could still have an specialization on for example, having a lot of fossil liquids in one mode, and very little in the other mode, and still respects the shares equation. If this is the intended behavior just disregard my comment.

**Comment by fschreyer** [comment]
> Why the shares are calculated on bio and synfuel only? Wouldn't you need to consider fossils also in the equation to enforce the same bio+syn on different modes?

I would only want to enforce these equal shares for carbon-neutral fuels. Once we use the emissions markets and have different carbon prices for e.g. trucks and bunkers, different shares of fossil fuels per sector are a meaningful endogenous model outcome.

**Review by Renato-Rodrigues — APPROVED** [review]

**Review by Loisel — APPROVED** [review]
Looks OK. Clever to write it in this way to avoid DIVBYZERO.

**Comment by fschreyer** [comment]
> Looks OK. Clever to write it in this way to avoid DIVBYZERO.

Taken from you from the equation above, Alois :)

**Pull request merged**
