### PR TITLE
Extend the time horizon for fixing fossil fuel trade to 2020.

### PR DESCRIPTION
**Pull request by nicobauer**
## Type of change

(Make sure to delete from the Type-of-change list the items not relevant to your PR)

- [ ] Bug fix 
- [ ] Refactoring
- [ ] New feature 
- [x ] Minor change (default scenarios show only small differences)
- [ ] Fundamental change
- [ ] This change requires a documentation update

## Checklist:

- [x ] My code follows the [coding etiquette](https://github.com/remindmodel/remind/blob/develop/main.gms#L80)
- [x ] I performed a self-review of my own code
- [x ] I explained my changes within the PR, particularly in hard-to-understand areas
- [x ] I checked that the [in-code documentation](https://github.com/remindmodel/remind/blob/develop/main.gms#L120) is up-to-date
- [ NA] I adjusted the reporting in [`remind2`](https://github.com/pik-piam/remind2) where it was needed
- [ NA] I adjusted `forbiddenColumnNames` in [readCheckScenarioConfig.R](https://github.com/remindmodel/remind/blob/develop/scripts/start/readCheckScenarioConfig.R) in case the PR leads to deprecated switches
- [ x] All automated model tests pass (`FAIL 0` in the output of `make test`)
- [NO; the link guides me to the magpie change-log, not the remind change-log ] The changelog `CHANGELOG.md` [has been updated correctly](https://gitlab.pik-potsdam.de/rse/rsewiki/-/wikis/Standards-for-Writing-a-Changelog)

## Further information (optional):

* Test runs are here: /p/projects/remind/users/nicolasb/remind3p2p2_prep/remind-1
* Comparison of results (what changes by this PR?): Changes in fossil trade

### CODE REVIEW

**Comment by LaviniaBaumstark** [comment]
are you sure that this works for our default scenarios? Please, make some test runs

**Comment by nicobauer** [comment]
It works, I made test runs. What makes you worry?
image

**Comment by LaviniaBaumstark** [comment]
nice, you never know with additional bounds in REMIND

**Review by LaviniaBaumstark — APPROVED** [review]

**Comment by nicobauer** [comment]
And this is the reason, why I did the test runs. I also wanted to see how things change.

**Comment by nicobauer** [comment]
Now, all that is left is to hit the green button "merge pull request", right?

**Pull request merged**
