### PR TITLE
Fix REMIND for running with no industry CCS

### PR DESCRIPTION
**Pull request by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q**
fix remindmodel/development_issues#349

### CODE REVIEW

**Review by JakobBD — APPROVED** [review]
Looks good. 
[`q37_limitOutflowCCPrc`](https://github.com/remindmodel/remind/pull/1835/files#diff-f2b7ce9b56bd63ff7c3e6805c6fc79f71d7a2900df47baeef0aae1a868f34775R453) could also be adapted. I tried myself, but getting domain violation errors. Still a GAMS syntax newbie, it seems.

**Comment by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q** [comment]
> [`q37_limitOutflowCCPrc`](https://github.com/remindmodel/remind/pull/1835/files#diff-f2b7ce9b56bd63ff7c3e6805c6fc79f71d7a2900df47baeef0aae1a868f34775R453) could also be adapted.


Adapted how?  I do not see the need.  Still a PBS newbie, it seems ;)

**Comment by JakobBD** [comment]
No need in terms of functionality, just code quality. 

The dollar condition on the equation domain served to define the equation only for actual CC tech, by checking that the tech appeared as a CC tech in `tePrc2teCCPrc`. Now that we have `teCCPrc` explicitly, it shouldn't be needed anymore. 
However, when I just delete the condition, I get domain violations in the sums below, which I don't understand the reason for.

**Comment by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q** [comment]
Never change a running system :p

**Pull request merged**
