### PR TITLE
make cement process emissions variable for conopt

### PR DESCRIPTION
**Pull request by JakobBD**
## Purpose of this PR

So far, cement process emissions were fixed to a value based on the previous iteration's `ue_cement`. 
`ue_cement` therefore only saw energy-related emissions as an incentive for reduction. 

This PR makes cement process emissions a function of ue_cement in the current iteration, such that CONOPT sees the incentive to reduce ue_cement.

I still have to check and clean up the fixing of `vm_macBase` and `vm_emiIndBase` in `core/presolve.gms`, as process cement CCS cost enters the budget equation twice right now. 

TBD if we like the results, and if we want to do some ad-hoc adaptation, e.g. to CES elasticities.  

## Type of change

(Make sure to delete from the Type-of-change list the items not relevant to your PR)

- [x] Bug fix 
- [ ] Refactoring
- [ ] New feature 
- [ ] Minor change (default scenarios show only small differences)
- [ ] Fundamental change
- [ ] This change requires a documentation update

## Checklist:

- [ ] My code follows the [coding etiquette](https://github.com/remindmodel/remind/blob/develop/main.gms#L80)
- [ ] I performed a self-review of my own code
- [ ] I explained my changes within the PR, particularly in hard-to-understand areas
- [ ] I checked that the [in-code documentation](https://github.com/remindmodel/remind/blob/develop/main.gms#L120) is up-to-date
- [ ] I adjusted the reporting in [`remind2`](https://github.com/pik-piam/remind2) where it was needed
- [ ] I adjusted `forbiddenColumnNames` in [readCheckScenarioConfig.R](https://github.com/remindmodel/remind/blob/develop/scripts/start/readCheckScenarioConfig.R) in case the PR leads to deprecated switches
- [ ] All automated model tests pass (`FAIL 0` in the output of `make test`)
- [ ] The changelog `CHANGELOG.md` [has been updated correctly](https://gitlab.pik-potsdam.de/rse/rsewiki/-/wikis/Standards-for-Writing-a-Changelog)

## Further information (optional):

* Test runs are here: `/p/tmp/jakobdu/remind_temp2`
* Comparison of results (what changes by this PR?): 

image

### CODE REVIEW

**Comment by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q** [comment]
I tested this too, same result (unsurprisingly).
image
Weird to see these differences between AMT and stock `develop` runs, though.
I do not see any point in adjusting CES elasticities over this.

**Review by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q — COMMENTED** [review]
In general I would split this in two: the small change of moving `vm_emiIndBase("co2cement_process")` from presolve into an equation, that has a lot of impact on model behaviour, and the large code shuffling involving `fixed_shares`, that has no influence on model behaviour at all.

**Comment by JakobBD** [comment]
Doing final tests on this after separating the fixed_shares refactoring (same directory as above, newest two runs). 
From my side ready to merge once these tests have passed.

**Comment by JakobBD** [comment]
Tests came back fine, ready to merge from my point of view.

**Review by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q — APPROVED** [review]

**Pull request merged**
