### PR TITLE
Merge back ariadne develop

### PR DESCRIPTION
**Pull request by fschreyer**
This merges the ariadne branch back with a number of changes

* refactoring and extending CES markup cost in industry fixed_shares and simple buildings, sets new CES markup cost to feeli node of 0.5 trUSD/TWa to increase efficiency in calibration and have another lever to influence electrification shares in fixed_shares industry, this requires recalibration, exact level of CES markup in industry and buildings should still be refined in a sector-specific validation, I think
* adaptation of H2 offset in simple buildings (by @rkrekeler ), requires recalibration
* add floor space in buildings
* adapt ariadne trade scenarios
* changes to H2 power storage ( by @robertpietzcker )
* extent switch to scale agricultural MAC emissions to all regions
* switch constraint for H2 buildings and industry t&d capacities to equality to avoid switching between H2 build and ind
* update aridane notebook for plots

...

### CODE REVIEW

**Review by rkrekeler — APPROVED** [review]
My changes to ` modules/36_buildings/simple/bounds.gms` were just for test purposes and are commented out. I should not have committed them to Felix' ariadne branch and they are not needed here.

**Comment by fschreyer** [comment]
> 
> 
> My changes to ` modules/36_buildings/simple/bounds.gms` were just for test purposes and are commented out. I should not have committed them to Felix' ariadne branch and they are not needed here.

Ok, I can remove those lines again.

**Comment by rkrekeler** [comment]
> 
> 
> > My changes to ` modules/36_buildings/simple/bounds.gms` were just for test purposes and are commented out. I should not have committed them to Felix' ariadne branch and they are not needed here.
> 
> Ok, I can remove those lines again.

Thanks!

**Review by LaviniaBaumstark — COMMENTED** [review]
In main.gms not all ariadne-switches seem to be in the default setting, maybe adjust the setting of the default.
Which version of CES-parameters (which sectoral detail, etc.) is the default one?

**Comment by fschreyer** [comment]
> In main.gms not all ariadne-switches seem to be in the default setting, maybe adjust the setting of the default.

done

> Which version of CES-parameters (which sectoral detail, etc.) is the default one?

I am not sure I understand the question. The default REMIND calibration is here ``/p/projects/remind/inputdata/CESparametersAndGDX/stat_off-indu_fixed_shares-buil_simple-tran_complex-POP_pop_SSP2-GDP_gdp_SSP2-Kap_debt_limit-Reg_62eff8f7.inc``. The ariadne calibration (REMIND-EU EDGE-T SSP2) is in the same folder.

**Comment by LaviniaBaumstark** [comment]
I wondered about the loaded CES parameters which were not the default settings

**Comment by fschreyer** [comment]
This just comes because I run setups different from standard calibration and it got commited by accident. Changed it back. We should at some point move these parts that get overwritten with each run (core/sets, main.gms, CES/datainput) out of git. Avoids confusions.

**Pull request merged**
