### PR TITLE
Revert "Merge pull request #452 from Loisel/fix/elh2_dynamic_efficiency"

### PR DESCRIPTION
**Pull request by Loisel**
This reverts commit 7f4699f5561ff4dbaf70c9de7ee68d226d1eea6d, reversing
changes made to 33e9beb000e7c553ac24f6aa095a73440f79447b.

### CODE REVIEW

**Comment by giannou** [comment]
I am currently running tests to see if also other configurations are broken, will have results in the next couple of hours

**Comment by Loisel** [comment]
Ok, following a suggestion by Marianna I'm doing a calibration run to see if it converges.

**Comment by giannou** [comment]
baseline runs are fine

**Comment by giannou** [comment]
SSP2-NDC and SSP5-NDC are also fine but your changes seem to be affecting SDP-NDC and SSP!-NDC. will confirm soon

**Comment by giannou** [comment]
> your changes seem to be affecting SDP-NDC and SSP1-NDC.

your changes are NOT affecting these scenarios, so far they only affect `testOneRegi` baseline runs for `EUR`

**Comment by Loisel** [comment]
Actually a "default" run seems to fail also.

**Comment by Loisel** [comment]
I don't know why it does not fail for some scenarios, but the error seems to arise from `elh2` not being set in `pm_eta_conv`, thus being quite a generic failure. See PR #460 . If some scenarios do not crash, it means that there is some manual setting of `elh2` in `pm_eta_conv`, maybe in the NDC module.

**Comment by Loisel** [comment]
Closing this as it is solved in #460

**Pull request closed without merging**
