### PR TITLE
add symlinks to MAGICC files

### PR DESCRIPTION
**Pull request by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q**
I'm still of the opinion that we can just add the MAGICC files, since you also get them on their website, but here goes:

In order to have a REMIND with on less source of constant failure (#180), we can add symlinks to the `./core/magicc/` directory.  The symlinks only contain the information where the files are to be found ([e.g.](https://github.com/0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q/remind/blob/feature/symlink_magicc/core/magicc/EDGAR_CH4_EMIS_LANDUSE.IN)), but no actual data.  When the run is assembled by `./scripts/start/prepare_and_run.R`, the `./core/magicc/` directory [is copied](https://github.com/remindmodel/remind/blob/3e4fc335245fc37c4ed0572eb4aee960a8c29182/scripts/start/prepare_and_run.R#L403) using `file.copy()` [which copies the targets of the links, not the links](https://stat.ethz.ch/R-manual/R-devel/library/base/html/files.html): 
> On a POSIX filesystem the targets of symbolic links will be copied rather than the links themselves

so we end up with proper MAGICC in the output directory, without any actuall MAGICC in the repository.

If this is agreeable, pick a proper place for the MAGICC files, not my home directory ;)

### CODE REVIEW

**Review by giannou — COMMENTED** [review]
Looks good to me, thanks Michaja. I would also very very strongly prefer to just bring back the MAGICC files. @LaviniaBaumstark

**Comment by giannou** [comment]
I put the files here: /p/projects/rd3mod/magicc
Shall we change the targets of the symbolic links to point there?

**Comment by giannou** [comment]
The MAGICC developers have a no-further-sharing restriction in their webpage: http://www.magicc.org/about/legalnotice
This means we can not upload the files here after all, right?

**Comment by giannou** [comment]
> I put the files here: /p/projects/rd3mod/magicc
> Shall we change the targets of the symbolic links to point there?

Also, RSE recommends to change the implementation in a way that no PIK-cluster-specific paths are found in the code. How about a config setting called `magicclocation` which contains the path to the local MAGICC files? In a more general note: is it necessary to copy the whole magicc folder into each run folder?

**Comment by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q** [comment]
> This means we can not upload the files here after all, right?

We would not upload files, only symlinks.

> Also, RSE recommends to change the implementation in a way that no PIK-cluster-specific paths are found in the code. How about a config setting called `magicclocation` which contains the path to the local MAGICC files?

Possible, yet pointless, since we cannot share "our" MAGICC files with anyone, and they can't get "our" MAGICC files in any other way, and dropping any other MAGICC files in there would produce different results, which we didn't test and aren't willing to accept as "REMIND results".

**Comment by giannou** [comment]
> > This means we can not upload the files here after all, right?
> 
> We would not upload files, only symlinks.
I was referring to the previous discussion about uploading the MAGICC files in the REMIND repository, of course I was not referring to the links
> 
> > Also, RSE recommends to change the implementation in a way that no PIK-cluster-specific paths are found in the code. How about a config setting called `magicclocation` which contains the path to the local MAGICC files?
> 
> Possible, yet pointless, since we cannot share "our" MAGICC files with anyone, and they can't get "our" MAGICC files in any other way, and dropping any other MAGICC files in there would produce different results, which we didn't test and aren't willing to accept as "REMIND results".

**Pull request closed without merging**
