### PR TITLE
Update REMIND-EU runs in scenario config rev3p0p0

### PR DESCRIPTION
**Pull request by fschreyer**
Update the EU runs according to the latest ariadne config. Should be able to run this now. 

Changes to the config file from compareScenConfig():

Not sure why the function shows changes for SDP scenarios. I kept them at zero in the start column how it was. 

```

Changes in the scenarios:
~ SDP-Base:
    start: 0 -> 1 (default: )
~ SDP-NDC:
    start: 0 -> 1 (default: )
~ SDP-NPi:
    start: 0 -> 1 (default: )
~ SDP-PkBudg500:
    start: 0 -> 1 (default: )
~ SDP-PkBudg1150:
    start: 0 -> 1 (default: )
~ EU21reg_Calib:
    cm_co2_tax_growth: 1.05 -> 1.025 (default: 1.05)
    cm_NucRegiPol: off -> on (default: off)
    cm_CoalRegiPol: off -> on (default: off)
    description: was changed (default: )
~ EU21reg_Base:
    start: 1 -> 0 (default: )
    cm_co2_tax_growth: 1.05 -> 1.025 (default: 1.05)
    cm_NucRegiPol: off -> on (default: off)
    cm_CoalRegiPol: off -> on (default: off)
    description: was changed (default: )
~ EU21reg_Ref-gd40:
    start: 1 -> 0 (default: )
    cm_iterative_target_adj: 5 -> 9 (default: 0)
    c_budgetCO2from2020: 1100 -> 820 (default: 1150)
    carbonprice: expoLinear -> diffCurvPhaseIn2Lin (default: none)
    cm_co2_tax_2020: 30 -> 100 (default: -1)
    cm_peakBudgYr: 2100 -> 2080 (default: 2050)
    cm_co2_tax_growth: 1.05 -> 1.025 (default: 1.05)
    path_gdx_ref: EU21reg_Base -> EU-SSP2EU_Base (default: )
    path_gdx_bau: EU21reg_Base -> EU-SSP2EU_Base (default: )
    description: was changed (default: )
~ EU21reg_Bal:
    start: 1 -> 0 (default: )
    c_budgetCO2from2020: 500 -> 570 (default: 1150)
    cm_co2_tax_2020: 100 -> 60 (default: -1)
    cm_peakBudgYr: 2080 -> 2045 (default: 2050)
    cm_co2_tax_growth: 1.05 -> 1.025 (default: 1.05)
    cm_CESMkup_build: fehob 1.75 -> feelhpb 1.32 (default: standard)
    cm_regiCO2target: 2020.2030.EU27_regi.year.netGHG_LULUCFGrassi_noBunkers 2.15, 2035.2050.EU27_regi.year.netGHG_LULUCFGrassi_noBunkers 0.01, 2020.2030.DEU.year.netGHG_noBunkers 0.46, 2035.2045.DEU.year.netGHG_noBunkers 0.001 -> 2020.2030.EU27_regi.year.netGHG_noBunkers 2.250, 2035.2050.EU27_regi.year.netGHG_noBunkers 0.01, 2020.2030.DEU.year.netGHG_noBunkers 0.46, 2035.2045.DEU.year.netGHG_noBunkers 0.001 (default: off)
    cm_EDGEtr_scen: Mix4 -> Mix3 (default: Mix1)
    path_gdx_ref: EU21reg_Ref-gd40 -> EU-SSP2EU_Ref (default: )
    path_gdx_bau: EU21reg_Ref-gd40 -> EU-SSP2EU_Base (default: )
    description: was changed (default: )
```

### CODE REVIEW

**Comment by orichters** [comment]
> Not sure why the function shows changes for SDP scenarios. I kept them at zero in the start column how it was.

No, you changed them from 1 to 0, see the git diff. May it be that you used `compareScenConf` function in the inverse way than intended? I think I implemented it with c("oldfile", "newfile"), and you probably called it with c("newfile", "oldfile") and therefore all the changes are exactly inverted? But I see the function description is not really good at this point.

**Comment by giannou** [comment]
Is that something that needs to be transferred to other scenario configs also?

**Comment by fschreyer** [comment]
No, it is the only config outside the 21_config folder which has REMIND-EU runs.

**Comment by giannou** [comment]
> No, it is the only config outside the 21_config folder which has REMIND-EU runs.

Thanks!

**Pull request merged**
