### PR TITLE
update renv/activate.R to 0.15.5

### PR DESCRIPTION
**Pull request by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q**
- [x] Minor change (default scenarios show only small differences)

### CODE REVIEW

**Comment by pfuehrlich-pik** [comment]
When checking out this PR I get
```
renv 0.15.4 was loaded from project library, but this project is configured to use renv 0.15.5.
Use `renv::record("renv@0.15.4")` to record renv 0.15.4 in the lockfile.
Use `renv::restore(packages = "renv")` to install renv 0.15.5 into the project library.
```
This could irritate some people and leave them unsure what to do, so I'd update renv only when necessary. Is there an important feature/bugfix in renv 0.15.5?

**Comment by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q** [comment]
> outdated (defined as "an update is available") packages

[[↑]](https://github.com/remindmodel/remind/pull/808#issuecomment-1128530734)

> Is there an important feature/bugfix in renv 0.15.5?

[Lots](https://github.com/remindmodel/remind/pull/808#issuecomment-1128530734), none of which I know to be relevant for REMIND.

The irritating message will show up when library and lockfile version diverge, whenever that may be.  Users also get irritating messages when they update their package library more regularly than the cluster library is updated.

**Comment by pfuehrlich-pik** [comment]
The updateRenv script, which is recommended for updates in the tutorial, will create a snapshot right after updating, so there won't be such a message. The message is also different when updating renv vs. any other package, although renv quite nicely tells you what to do, so it's probably not a big deal.
That being said, I'd be the last one to oppose frequent updates. It's just not what some (most?) REMIND users want usually. What's your take on this @LaviniaBaumstark ?

**Comment by LaviniaBaumstark** [comment]
For now I would not update. Would be different if we would know of a fix which is necessary for us. Let's try to not confuse people starting to work with renv

**Pull request closed without merging**
