### PR TITLE
remove deltaCap time split for vm_capCum

### PR DESCRIPTION
**Pull request by tabeado**
## Purpose of this PR
Follow up on the removal of the deltaCap time split implemented by Robert (PR #1238). q_capCumNet and the calculation of p22_marginalCapcumBenefit are adjusted to be consistent with the new implementation of deltaCap.

## Type of change

(Make sure to delete from the Type-of-change list the items not relevant to your PR)

- [x] Bug fix 
- [ ] Refactoring
- [ ] New feature 
- [x] Minor change (default scenarios show only small differences)
- [ ] Fundamental change
- [ ] This change requires a documentation update

## Checklist:

- [x] My code follows the [coding etiquette](https://github.com/remindmodel/remind/blob/develop/main.gms#L80)
- [x] I performed a self-review of my own code
- [x] I explained my changes within the PR, particularly in hard-to-understand areas
- [ ] I checked that the [in-code documentation](https://github.com/remindmodel/remind/blob/develop/main.gms#L120) is up-to-date
- [ ] I adjusted the reporting in [`remind2`](https://github.com/pik-piam/remind2) where it was needed
- [ ] I adjusted `forbiddenColumnNames` in [readCheckScenarioConfig.R](https://github.com/remindmodel/remind/blob/develop/scripts/start/readCheckScenarioConfig.R) in case the PR leads to deprecated switches
- [ ] All automated model tests pass (`FAIL 0` in the output of `make test`)

## Further information (optional):

* Test runs are here:  /p/tmp/tabeado/deltaCapCleanup/remind/output
* Comparison of results (what changes by this PR?):

### CODE REVIEW

**Comment by tabeado** [comment]
The effects appear to be generally very small. The main exception are prices for hydrogen (see e.g. p.92 & p. 115 in /p/tmp/tabeado/deltaCapCleanup/remind/output/compScen-fullComp-2023-04-06_08.43.12-H12.pdf

**Comment by cchrisgong** [comment]
Our H2 price is kind of weird - isn't it being discussed in mattermost? SE H2 price collapses under NDC for SSA and for EUR - probably just because we are using old calibration? I.e. calibration would have constant demand, and H2 supply is lower in NDC run, so price collapse...  if there is a short compscen (plot until 2050) then one can see it clearer probably..
image

**Comment by tabeado** [comment]
Chris, I added the short compareScenarios2: P:\deltaCapCleanup\remind\output\compScen-FullCompShort-2023-04-06_11.05.22-H12-short

**Review by cchrisgong — APPROVED** [review]

**Comment by LaviniaBaumstark** [comment]
what is the status of this PR? will you continue working on it?

**Comment by cchrisgong** [comment]
there are small but visible changes: more VRE capacity under baseline, and more electricity under 1.5C
/p/tmp/tabeado/deltaCapCleanup/remind/output

image

image

This looks reasonable to me, as usually deltacap(T+1) is larger than deltacap(T)  for VRE in the first half of the century, so when this changes involve cumulative capacity going from .5* deltacap(T+1) + 0.5* deltacap(T) to deltacap(T+1), it will increase wind and solar deployment because they are learned faster based on higher cumulative capacities. This will decrease electricity price under 1.5C to increase electrification

**Review by cchrisgong — APPROVED** [review]

**Pull request merged**
