### PR TITLE
Ensure library requirements are installed before running tests; add make target

### PR DESCRIPTION
**Pull request by mikapfl**
## Purpose of this PR

If a new requirement (e.g. new library or newer version) is added to develop, and then someone else pulls develop and runs `make test`, it just hangs because remind asks about installing the new library and the tests hide the question. Most recently, this happened with `reticulate`.

With this PR, we now make sure that the REMIND requirements are met before running tests.

## Type of change

- [x] Bug fix 
- [x] Refactoring

## Checklist:

- [x] My code follows the [coding etiquette](https://github.com/remindmodel/remind/blob/develop/main.gms#L80)
- [x] I performed a self-review of my own code
- [x] I explained my changes within the PR, particularly in hard-to-understand areas
- [x] I checked that the [in-code documentation](https://github.com/remindmodel/remind/blob/develop/main.gms#L120) is up-to-date
- [x] All automated model tests pass (`FAIL 0` in the output of `make test`)

### CODE REVIEW

**Review by orichters — APPROVED** [review]
What I did for testing it:
- uninstall `piamenv` package -> reasonable error message
- install old version of `piamenv` -> reasonable error message
- uninstall `remind2` -> `make test` manages to fix that
- install old version of `remind2` -> `make test` manages to fix that

I'm not sure whether it makes sense that I can say `no` to the question by `make test` whether I want to update but it proceeds with the tests – and it seems this is not how it is intended in `setup_updateRenv.R`.
```
  remind2 >= 1.104.1 is required, but 1.104.0 is installed - please update: remind2
Try to fix automatically? (Y/n): n
make[1]: Leaving directory '/p/tmp/oliverr/remind-mikapfl'
✔ | F W S  OK | Context
✔ |         3 | 01-combine_slurmConfig
✔ |     1   1 | 01-gms_readSettings [0.1s]
…
```

**Comment by mikapfl** [comment]
> I'm not sure whether it makes sense that I can say no to the question by make test whether I want to update but it proceeds with the tests – and it seems this is not how it is intended in setup_updateRenv.R.

True, that is not really useful, but it is the same when you try to directly start remind, no? It asks you if it should fix it, and if you say no, it just carries on.

**Comment by mikapfl** [comment]
Actually, my intention was that tests don't ask, just install necessary updates automatically. Fixed.

**Comment by orichters** [comment]
I'm not sure whether this is the right choice. I'm not sure about other libraries, but for example `remind2` can be a bit sensitive because you may want to have harmonized reporting. In particular, because the script is not installing only the required package version, but the newest it can find (is that intended, by the way?). I'm reluctant to updating packages automatically in case you run an innocent `make test` (and I can imagine people having strong opinions about that :)). Or, framed differently: If we accept that people run `./start.R` without updating the libraries (so there seem to be a reason we don't always update automatically), then `make test` shouldn't do it automatically.

**Comment by mikapfl** [comment]
I don't feel strongly either way, so I just reverted it to the asking behaviour, but now intended. :wink:

**Review by orichters — APPROVED** [review]
fine from my side, big improvement compared to endless tests that do not even fail

**Pull request merged**
