### PR TITLE
target convergence check and some commenting

### PR DESCRIPTION
**Pull request by fschreyer**
Add convergence check of regional and global target to nash and add some commenting to calibration switches

### CODE REVIEW

**Comment by giannou** [comment]
which input data revision is this version supposed to work with? I wanted to test it and get the following error:
```
Load data..
  try /p/projects/rd3mod/inputdata/output
Following files not found:
  rev5.979_62eff8f7_remind.tgz

```

**Comment by fschreyer** [comment]
Not sure why. I just pulled this from the trunk. 
```
#### Current input data revision (<mainrevision>.<subrevision>) ####
cfg$revision <- 5.98312
```

**Comment by fschreyer** [comment]
Although I remember having an issue in this branch with input data. It was downloading it into the input folder of the main folder but not distributing it into the input folders of some of the modules. Not sure, maybe that helps and is related.

**Comment by LaviniaBaumstark** [comment]
delete the file source_files.log in remind/input and try again. If it already downloaded the input data it will get this information from this file and does not download the input data again.

**Comment by fschreyer** [comment]
I pulled from the main repo again, tested default runs and it works for me.

**Comment by fschreyer** [comment]
Ah, I didnt see there was a pending merge conflict. I resolved that. Should be fine to merge now.

**Review by LaviniaBaumstark — APPROVED** [review]

**Pull request merged**
