### PR TITLE
delete outdated scenario_config_*.csv file

### PR DESCRIPTION
**Pull request by LaviniaBaumstark**
## Purpose of this PR
cleaning

## Type of change

(Make sure to delete from the Type-of-change list the items not relevant to your PR)

- [x] Refactoring

## Checklist:

- [x] My code follows the [coding etiquette](https://github.com/remindmodel/remind/blob/develop/main.gms#L80)
- [x] I performed a self-review of my own code

## Further information (optional):

* Test runs are here: 
* Comparison of results (what changes by this PR?):

### CODE REVIEW

**Comment by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q** [comment]
https://mattermost.pik-potsdam.de/rd3/pl/xg5bfcf6ftdb8mw5xbt6nczkuc

**Comment by LaviniaBaumstark** [comment]
talked to Gunnar and Chris, she will upload a new config file for deep EL scenarios soon

**Comment by cchrisgong** [comment]
I'll get to it next week :)

**Comment by LaviniaBaumstark** [comment]
@cchrisgong may I already merge this?

**Review by cchrisgong — APPROVED** [review]

**Review by fbenke-pik — APPROVED** [review]

**Pull request merged**
