### PR TITLE
calculate prices also before cm_startyear to always have all prices after 2005 in reporting

### PR DESCRIPTION
**Pull request by fschreyer**
Adresses [this issue](https://github.com/remindmodel/development_issues/issues/61). 

* changes time set over which prices are calculated
* removes some old initializations of price parameters which are not needed anymore as any input gdx features them
* committed file renaming of DTcoupl power realization which pops up for everyone currently

See mifs from test run here ``/p/tmp/schreyer/Modeling/REMIND_H12/Current/output/SSP2-PkBudg1520_PriceStart_2021-11-18_21.32.20``

### CODE REVIEW

**Review by cchrisgong — APPROVED** [review]
oops, thanks for committing DTcoup

**Comment by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q** [comment]
> See mifs from test run here `/p/tmp/schreyer/Modeling/REMIND_H12/Current/output/SSP2-PkBudg1520_PriceStart_2021-11-18_21.32.20`

Doesn't work for at least 36 variables:

```R
library(tidyverse)
library(quitte)

d <- read.quitte(c('/tmp/REMIND_generic_SSP2-Base_PriceStart_withoutPlus.mif',
                   '/tmp/REMIND_generic_SSP2-PkBudg1520_PriceStart_withoutPlus.mif'))

d %>% 
    filter(grepl('^Price', variable),
           !grepl('Moving Avg', variable),
           2020 >= period) %>% 
    select(scenario, region, variable, period, value) %>% 
    pivot_wider(names_from = 'scenario') %>% 
    mutate(match = `SSP2-Base_PriceStart` == `SSP2-PkBudg1520_PriceStart`) %>% 
    group_by(variable) %>%
    filter(!all(match)) %>% 
    ungroup() %>% 
    distinct(variable) %>% 
    pull(variable) %>% 
    sort() %>% 
    sub('(.*)', '`\\1`', .) %>% 
    paste(collapse = '\n') %>% 
    cat()
```
`Price|Final Energy|Buildings|Electricity`
`Price|Final Energy|Buildings|Gases`
`Price|Final Energy|Buildings|Liquids`
`Price|Final Energy|Buildings|Solids`
`Price|Final Energy|Industry|Electricity`
`Price|Final Energy|Industry|Gases`
`Price|Final Energy|Industry|Hydrogen`
`Price|Final Energy|Industry|Liquids`
`Price|Final Energy|Industry|Solids`
`Price|Final Energy|Transport|Electricity`
`Price|Final Energy|Transport|Gases`
`Price|Final Energy|Transport|Hydrogen`
`Price|Final Energy|Transport|Liquids`
`Price|Final Energy|Transport|Liquids|HDV`
`Price|Final Energy|Transport|Liquids|LDV`
`Price|Primary Energy|Biomass|1st Generation|Oil-based`
`Price|Primary Energy|Biomass|1st Generation|Sugar and Starch`
`Price|Primary Energy|Biomass|Modern`
`Price|Primary Energy|Coal`
`Price|Primary Energy|Gas`
`Price|Primary Energy|Nuclear`
`Price|Primary Energy|Oil`
`Price|Secondary Energy|Electricity`
`Price|Secondary Energy|Gases`
`Price|Secondary Energy|Gases|Biomass`
`Price|Secondary Energy|Gases|Fossil`
`Price|Secondary Energy|Gases|Hydrogen`
`Price|Secondary Energy|Heat`
`Price|Secondary Energy|Hydrogen`
`Price|Secondary Energy|Liquids`
`Price|Secondary Energy|Liquids|Biomass`
`Price|Secondary Energy|Liquids|Fossil`
`Price|Secondary Energy|Liquids|Hydrogen`
`Price|Secondary Energy|Solids`
`Price|Secondary Energy|Solids|Biomass`
`Price|Secondary Energy|Solids|Fossil`

**Comment by fschreyer** [comment]
Mhm, I see them in the mif

image

**Comment by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q** [comment]
… but that only affects `IND`, since `qm_budget.m` is all zeros.

Not sure how the baseline run is calculating its prices, but they could be loaded (and later overwritten if possible) using
```
execute_load "input_bau.gdx", p_PEPrice, p_SEPrice, p_FEPrice;
```

**Review by Loisel — APPROVED** [review]
Looks okay, but did not test it. the `TDcoup` stuff seems unrelated.

**Pull request merged**
