### PR TITLE
add a copy of fulldata.gdx with scenario names for quick post-processing

### PR DESCRIPTION
**Pull request by cchrisgong**
# Purpose of this PR
simply adding a copy of fulldata.gdx in the output folder with scenario name

## Type of change

(Make sure to delete from the Type-of-change list the items not relevant to your PR)

- [ X] Minor change (default scenarios show only small differences)

## Checklist:

- [x] My code follows the coding etiquette
- [x] I have performed a self-review of my own code
- [x] Changes are commented, particularly in hard-to-understand areas
- [x] I have updated the in-code documentation
- [x] I have adjusted reporting where it was needed
- [x] All automated model tests pass (`FAIL 0` in the output of `make test`)

## Further information (optional):

* Test runs are here: 
* Comparison of results (what changes by this PR?):

### CODE REVIEW

**Comment by dklein-pik** [comment]
Hi @cchrisgong, I'd like to learn more about what you need the gdx copy for. Maybe we can find a solution that does not require a copy. Thank you.

**Comment by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q** [comment]
> Maybe we can find a solution that does not require a copy.

Any of 
```
$ dumpgdx fulldata.gdx c_expname
Set,c_expname(*) c_expname as set for use in GDX 
C_SSP2EU-Base-rem-1
```
or
```
> quitte::read.gdx('fulldata.gdx', 'c_expname')$X.
[1] "C_SSP2EU-Base-rem-1"
```
or
```
c(gdx::readGDX('fulldata.gdx', 'c_expname'))
[1] "C_SSP2EU-Base-rem-1"
```

**Comment by orichters** [comment]
Hey Chris, I have to admit that I am not sure whether this would have 
any impact on anything (just a guess: If you use as scenario name "03", 
it could interfere with `c_keep_iteration_gdxes` or the calibration 
stuff. Please ask Lavinia or somebody with a better overview for an 
approval. Thanks…

**Comment by cchrisgong** [comment]
thanks, both
e.g. I would like to download a number of fulldata.gdx from various scenarios into the same folder locally and process them in a loop. If they are all called fulldata.gdx I usually have to manually rename them when I scp. I could write a shell script that does the renaming automatically, but it seems cumbersome

**Comment by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q** [comment]
```
$ for p in $( ssh -Ci ~/.ssh/cluster_lt547_rsa cluster.pik-potsdam.de "ls -1dF /p/projects/remind/modeltests/output/SSP2EU-AMT-*_2023-01-14*/fulldata.gdx" ); do n=$( echo "$p" | sed 's|.*/output/\(.*\)_20.*|fulldata_\1.gdx|' ); scp -i ~/.ssh/cluster_lt547_rsa "cluster.pik-potsdam.de:$p" "$n"; done
```
Adjust for you SSH key and the directory you want your files from.

**Comment by cchrisgong** [comment]
That worked, Thanks Michaja!

**Pull request closed without merging**
