### PR TITLE
Update and document CO2 capture rates and costs of X-to-Liquids / X-to-Gases technologies

### PR DESCRIPTION
**Pull request by fschreyer**
## Purpose of this PR

This addresses the [issue on carbon flows in the energy system](https://github.com/remindmodel/development_issues/issues/335). It is related to #1876. 

In particular, this PR adapts the CO2 capture rates of different X-to-Liquids and X-Gases technologies assuming that only 10% of the input carbon are lost (vented) during the gasification / syngas production step (consistent with X-to-H2 w/  capture technologies) and only 5% are lost during the follow-up step of FT-synthesis or methanation. This changes co2 capture rates as follows:

* increase bioftcrec: capture rate to 14.6 GtC/ZJ: 58% of carbon input 
* increase biogasc capture rate to 14.1 GtC/ZJ: 56% of carbon input 
* decrease coalftcrec capture rate to 15.8 GtC/ZJ (60%)
* decrease gasftcrec capture rate to 0.2 GtC/ZJ (1.3%)

CCU technologies (synthetic liquids and synthetic gas production) now also see carbon efficiency of 95%, i.e. 5% of captured carbon does not end up in output fuel.

Moreover, costs of some of the technologies are modified. 

* CAPEX/OPEX of synthetic liquids and synthetic gas technologies back to original parameterization based on Agora (2018)
* slightly lower bioftcrec CAPEX in line with Liu et al. 
* lower gasftrec/gasftcrec CAPEX  in line with assumptions for Coal-to-Liquids / Gas-to-H2 technologies

Please see [issue](https://github.com/remindmodel/development_issues/issues/335) for comparison plots of results. 

## Type of change

(Make sure to delete from the Type-of-change list the items not relevant to your PR)

- [x] Bug fix 

## Checklist:

- [x] My code follows the [coding etiquette](https://github.com/remindmodel/remind/blob/develop/main.gms#L80)
- [x] I performed a self-review of my own code
- [x] I explained my changes within the PR, particularly in hard-to-understand areas
- [x] I checked that the [in-code documentation](https://github.com/remindmodel/remind/blob/develop/main.gms#L120) is up-to-date
- [x] I adjusted the reporting in [`remind2`](https://github.com/pik-piam/remind2) where it was needed
- [x] I adjusted `forbiddenColumnNames` in [readCheckScenarioConfig.R](https://github.com/remindmodel/remind/blob/develop/scripts/start/readCheckScenarioConfig.R) in case the PR leads to deprecated switches
- [x] All automated model tests pass (`FAIL 0` in the output of `make test`)
- [x] The changelog `CHANGELOG.md` [has been updated correctly](https://gitlab.pik-potsdam.de/rse/rsewiki/-/wikis/Standards-for-Writing-a-Changelog)

## Further information (optional):

* Test runs are here: 
* Comparison of results (what changes by this PR?): 
``/p/tmp/schreyer/Modeling/remind/NewDevs/compScen-BioTechUpdateNew-2024-11-12_10.25.16-H12.pdf``

### CODE REVIEW

**Review by robertpietzcker — APPROVED** [review]
Looks good - thanks a lot!

**Comment by robertpietzcker** [comment]
oh, and could you move the runs and compScen to /p/projects/remind/ and adjust the path in the PR description?

**Comment by robertpietzcker** [comment]
oh, and as you reminded me of it - I guess it would be good to update SSP1/SSP3 tech parameters as well, no?

**Comment by fschreyer** [comment]
I talked to @amerfort. We will merge it now and might discuss further based on the next results.

**Comment by fschreyer** [comment]
SSP differentiation is still open and will be added later.

**Comment by lecfab** [comment]
Just to point out that this PR did not change the sources of liquids and gases too much:

image
image

**Pull request merged**
