### PR TITLE
undo 'increase memory on single node runs' #1567

### PR DESCRIPTION
**Pull request by orichters**
## Purpose of this PR

- undo https://github.com/remindmodel/remind/pull/1567
- close https://github.com/remindmodel/development_issues/issues/251
- fixed with https://github.com/pik-piam/remind2/pull/557

## Type of change

- [x] undo temporary fix

## Checklist:

- [x] I explained my changes within the PR, particularly in hard-to-understand areas
- [x] All automated model tests pass (`FAIL 0` in the output of `make test`)
- [ ] [test_06-output.R](https://github.com/remindmodel/remind/blob/master/tests/testthat/test_06-output.R) fails. That is normally not part of `make test`, but I ran it anyway because the reporting was changes. Is probably caused by some recent changes in remind2. Fail log is `/p/tmp/oliverr/remind/output/testOneRegi/log_output.txt`.

```
### start generation of mif files at 2024-03-12 18:39:30
running reportMacroEconomy...
running reportTrade...
running reportPE...
running reportSE...
running reportFE...
running reportExtraction...
running reportCapacity...
running reportCapitalStock...
running reportEnergyInvestment...
running reportEmiAirPol...
running reportEmi...
Error in `.dimextract()`:
! subscript out of bounds ("seliqbio.fegas.indst.ETS", "seliqbio.fesos.indst.ETS", "seliqsyn.fegas.indst.ETS", "seliqsyn.fesos.indst.ETS", "sesobio.fegas.indst.ETS", "sesobio.fehos.indst.ETS", "seel.fegas.indst.ETS", "seel.fehos.indst.ETS", "seel.fesos.indst.ETS", "seh2.fegas.indst.ETS", "seh2.fehos.indst.ETS", "seh2.fesos.indst.ETS", "segabio.fehos.indst.ETS", "segabio.fesos.indst.ETS", "segasyn.fehos.indst.ETS", "segasyn.fesos.indst.ETS", "sehe.fegas.indst.ETS", "sehe.fehos.indst.ETS", "sehe.fesos.indst.ETS")
Backtrace:
    ▆
 1. └─remind2::convGDX2MIF(...)
 2.   ├─magclass::mbind(...)
 3.   └─remind2::reportEmi(gdx, output, regionSubsetList, t)
 4.     ├─vm_demFeSector[, , getNames(vm_demFENonEnergySector)]
 5.     └─vm_demFeSector[, , getNames(vm_demFENonEnergySector)]
 6.       └─magclass (local) .local(x, i, j, ..., drop = drop)
 7.         └─magclass:::.dimextract(x, k, 3, pmatch = pmatch, invert = invert)
Execution halted
```

### CODE REVIEW

**Comment by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q** [comment]
> The moment at happens again, I will work on fixing it.

[[↑]](https://github.com/pik-piam/remind2/pull/557#issuecomment-1991684800)

That did not take long `:)`

**Comment by fbenke-pik** [comment]
On it

**Comment by fbenke-pik** [comment]
Should be fixed with https://github.com/pik-piam/remind2/pull/563

**Review by fbenke-pik — APPROVED** [review]
Thank you! Did the test succeed this time?

**Pull request merged**
