### PR TITLE
add missing columns cm_implicitQttyTarget, cm_emiMktTarget, cm_altFeEmiFac to DeepEl scenario config

### PR DESCRIPTION
**Pull request by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q**
- [x] Bug fix 

## Checklist:

- [x] My code follows the [coding etiquette](https://github.com/remindmodel/remind/blob/develop/main.gms#L80)
- [ ] I performed a self-review of my own code
- [x] I explained my changes within the PR, particularly in hard-to-understand areas
- [x] I checked that the [in-code documentation](https://github.com/remindmodel/remind/blob/develop/main.gms#L120) is up-to-date
- [x] I adjusted the reporting in [`remind2`](https://github.com/pik-piam/remind2) where it was needed
- [x] I adjusted `forbiddenColumnNames` in [readCheckScenarioConfig.R](https://github.com/remindmodel/remind/blob/develop/scripts/start/readCheckScenarioConfig.R) in case the PR leads to deprecated switches
- [x] All automated model tests pass (`FAIL 0` in the output of `make test`)
- [x] The changelog `CHANGELOG.md` [has been updated correctly](https://gitlab.pik-potsdam.de/rse/rsewiki/-/wikis/Standards-for-Writing-a-Changelog)

### CODE REVIEW

**Comment by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q** [comment]
bump @cchrisgong

**Comment by cchrisgong** [comment]
thanks, Michaja! sorry for the delay. These switches look like they are EU specific targets? Should they be in all Deep_El which is a global scenario? Are they legally bound targets? maybe they should be in a separate deepEl_eur config?
dankee

**Comment by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q** [comment]
These are switches introduced into the default scenarios in `scenario_config.csv` after DeepEl was run.  Unless there is a rationale for excluding/altering them from the values in the default scenarios, they should be included with DeepEl as well, no?

**Comment by cchrisgong** [comment]
@LaviniaBaumstark

**Comment by cchrisgong** [comment]
Lavinia said config.csv should be always aligned with main.gms. These switches she is not aware of. I believe their values in scenario_config.csv and in main.gms are not the same (so two different "default"). Would like to know if we need to change it where, or how to move forward with this PR

**Comment by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q** [comment]
> Unless there is a rationale for excluding/altering them from the values in the default scenarios, they should be included with DeepEl as well, no?

**Comment by LaviniaBaumstark** [comment]
can this PR be closed?

**Comment by cchrisgong** [comment]
still thinks cm_implicitQttyTarget in the config csv should be default and not contain EU switches.. @0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q ?

**Comment by LaviniaBaumstark** [comment]
is this PR also relevant for our next release? Will it be merged soon?

**Comment by cchrisgong** [comment]
Not relevant, I think someone is supposed to approve it maybe @0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q ?

**Pull request closed without merging**
