### PR TITLE
Bugfix: adjust conversion efficiencies and electricity co-production factors of bioliquids production w/ and w/o CCS

### PR DESCRIPTION
**Pull request by merfort**

### CODE REVIEW

**Comment by nicobauer** [comment]
HI Leon, oucld you please check whether the joint production factors are reasonable? THis is related to the electricity co-production and the need for the compression power. Thanks, Nico

**Comment by merfort** [comment]
Good point. I checked joint production factors for electricity co-production and adjusted them slightly to match the values given in Liu et al. (2011) "Making Fischer−Tropsch Fuels and Electricity from Coal and Biomass: Performance and Cost Analysis".

**Comment by nicobauer** [comment]
Cross checked with @merfort over phone.

**Comment by nicobauer** [comment]
The changes are sound.

**Review by nicobauer — APPROVED** [review]

**Pull request merged**
