### PR TITLE
Calibration fixes: scaling edge-t non-energy costs and setting dynamic vm_cesIO lower bounds    

### PR DESCRIPTION
**Pull request by Renato-Rodrigues**
- Adding dampening factor to align edge-t non-energy transportation costs with historical GDP data
- Setting dynamic lower bounds on vm_cesIO during the calibration, taking values computed using the Euler identity into consideration (Michaja)

### CODE REVIEW

**Comment by Renato-Rodrigues** [comment]
still pending:

- [ ] update the input data revision number: 
       Requirements: 
       - Merge [this](https://github.com/pik-piam/mrremind/pull/254) pull request to mrremind
       - Create new input data
       - update the default config with the input data revision number
- [ ] copy calibration files to the cluster repository
       Requirements: 
       - Wait for H12 calibration to finish
       - Wait for EU21 calibration to finish

**Review by LaviniaBaumstark — CHANGES_REQUESTED** [review]
we still need to find a general solution for sameas(regi,"SSA"), maybe comment it out for now, as it is not needed for default runs

**Comment by Renato-Rodrigues** [comment]
> we still need to find a general solution for sameas(regi,"SSA"), maybe comment it out for now, as it is not needed for default runs

@0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q any comment on that? 
Could we merge the PR as it is for now, and fix this afterwards. I don't believe I have enough time to handle these things quickly and still provide something that could be used by the projects still today.

**Comment by Renato-Rodrigues** [comment]
Actually I don't think we even need the hard coded code part. @0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q  is it not the case?
Wouldn't your code addition at [modules/29_CES_parameters/calibrate/bounds.gms](https://github.com/remindmodel/remind/pull/765/files#diff-39729b4849d6aa272dd2b170b12f2901b1dd7fddbce8652b599c548aa6733433) make the code in [modules/01_macro/singleSectorGr/bounds.gms](https://github.com/remindmodel/remind/pull/765/files#diff-e38ab6d6d1136bab141ccc4abe5b3d81fe9217a1eaa033b8a75d3c6cde131bb3) obsolete?

**Comment by Renato-Rodrigues** [comment]
> we still need to find a general solution for sameas(regi,"SSA"), maybe comment it out for now, as it is not needed for default runs

I removed the SSA specific code from this pull request so we can merge it, and wait for further tests to check if this code is actually necessary.
https://github.com/remindmodel/remind/pull/765/commits/c923381e042d53398682ad468493f2f0afed64fb

**Review by LaviniaBaumstark — APPROVED** [review]

**Pull request merged**
