### PR TITLE
fail tests if manipulating main.gms with default cfg drops/changes switches

### PR DESCRIPTION
**Pull request by orichters**
## Purpose of this PR

- It was noticed that some switches were not working properly in main.gms, if some comments looked like code assignment, see:
  - https://github.com/pik-piam/lucode2/issues/203
  - https://github.com/pik-piam/lucode2/issues/121
- This PR fixes two such occurrences and adds a test, making sure it will not happen again
- The tests copies main.gms to a tempfile, reads the default cfg and adjusts the tempfile according to this cfg. Then, it reads the cfg from the tempfile. This should be identical to the default cfg again.

## Type of change

- [x] Bug fix 
- [x] New feature 

## Checklist:

- [x] My code follows the [coding etiquette](https://github.com/remindmodel/remind/blob/develop/main.gms#L80)
- [x] I performed a self-review of my own code
- [x] I explained my changes within the PR, particularly in hard-to-understand areas
- [x] I checked that the [in-code documentation](https://github.com/remindmodel/remind/blob/develop/main.gms#L120) is up-to-date
- [x] I adjusted the reporting in [`remind2`](https://github.com/pik-piam/remind2) where it was needed
- [x] I adjusted `forbiddenColumnNames` in [readCheckScenarioConfig.R](https://github.com/remindmodel/remind/blob/develop/scripts/start/readCheckScenarioConfig.R) in case the PR leads to deprecated switches
- [x] All automated model tests pass (`FAIL 0` in the output of `make test`)
- [x] The changelog `CHANGELOG.md` [has been updated correctly](https://gitlab.pik-potsdam.de/rse/rsewiki/-/wikis/Standards-for-Writing-a-Changelog)

### CODE REVIEW

**Review by cchrisgong — APPROVED** [review]
Thank you soo much! :D

**Review by tonnrueter — APPROVED** [review]

**Comment by orichters** [comment]
This is how it looks if you run this new test without the fixes:
```
Warning (test_01-manipulateConfig.R:20:7): manipulate config with default configuration does not change main.gms
Applying manipulateConfig with the default configuration leads to this diff between main.gms and main9105c4a453e9f.gms:
<   cm_iteration_max          "number of iterations, if optimization is set to negishi or testOneRegi; is overwritten in Nash mode, except for cm_nash_autoconverge = 0"
>   cm_iteration_max          "number of iterations, if optimization is set to negishi or testOneRegi; is overwritten in Nash mode, except for cm_nash_autoconverge = 1"
< $setGlobal cm_fxIndUe        off  !! def = off
< $setGlobal cm_fxIndUeReg     ""       !! def = ""

Failure (test_01-manipulateConfig.R:24:5): manipulate config with default configuration does not change main.gms
length(diffresult) not equal to 0.
1/1 mismatches
[1] 4 - 0 == 4

Warning (test_01-manipulateConfig.R:30:5): manipulate config with default configuration does not change main.gms
These cfg$gms switches can't be found after manipulation of main.gms, see main9105c4a453e9f.gms.
Please file an issue in the gms package and try to adjust the code until the error goes away:
- cm_fxIndUe
- cm_fxIndUeReg

Failure (test_01-manipulateConfig.R:34:3): manipulate config with default configuration does not change main.gms
length(removedgms) not equal to 0.
1/1 mismatches
[1] 2 - 0 == 2
```
I shortly discussed with Tonn about the fact that `diff` might not be available on Windows, but we agreed that we can live with that for now.

**Comment by cchrisgong** [comment]
Thanks, this warning message would be found in log.txt?

**Comment by cchrisgong** [comment]
is it also applied to other module declarations or only in core?

**Comment by orichters** [comment]
- This whole problem should only be relevant for `main.gms`.
- You find the error if you run `make test`.

**Pull request merged**
