### PR TITLE
Patch to cost refacturing for SSP1 SSP5

### PR DESCRIPTION
**Pull request by cchrisgong**
## Purpose of this PR
Patch and debug SSP1 and SSP5 run in trunk after refactoring core/datainput.gms

1) fix compilation errors in SSP1 and SSP5
2) fix INFES errors in SSP1 and SSP5
3) fix comment asteriks issue
4) make comparison of pm_data(inco0) and other parameters systematically

diff testOneRegi_SSP1_dev_2024-02-27_16.29.42/compare_refac.put testOneRegi_SSP1_cost_2024-02-27_16.33.53/compare_refac.put

diff testOneRegi_SSP2EU_dev_2024-02-27_16.30.04/compare_refac.put testOneRegi_SSP2EU_cost_2024-02-27_16.34.12/compare_refac.put

diff testOneRegi_SSP5_dev_2024-02-27_16.30.23/compare_refac.put testOneRegi_SSP5_cost_2024-02-27_16.34.31/compare_refac.put

## Type of change

(Make sure to delete from the Type-of-change list the items not relevant to your PR)

- [ X] Bug fix 
- [ ] Refactoring
- [ ] New feature 
- [ ] Minor change (default scenarios show only small differences)
- [ ] Fundamental change
- [ ] This change requires a documentation update

## Checklist:

- [ ] My code follows the [coding etiquette](https://github.com/remindmodel/remind/blob/develop/main.gms#L80)
- [ ] I performed a self-review of my own code
- [ ] I explained my changes within the PR, particularly in hard-to-understand areas
- [ ] I checked that the [in-code documentation](https://github.com/remindmodel/remind/blob/develop/main.gms#L120) is up-to-date
- [ ] I adjusted the reporting in [`remind2`](https://github.com/pik-piam/remind2) where it was needed
- [ ] I adjusted `forbiddenColumnNames` in [readCheckScenarioConfig.R](https://github.com/remindmodel/remind/blob/develop/scripts/start/readCheckScenarioConfig.R) in case the PR leads to deprecated switches
- [ ] All automated model tests pass (`FAIL 0` in the output of `make test`)
- [ ] The changelog `CHANGELOG.md` [has been updated correctly](https://gitlab.pik-potsdam.de/rse/rsewiki/-/wikis/Standards-for-Writing-a-Changelog)

## Further information (optional):

* Test runs are here: 
* Comparison of results (what changes by this PR?):

### CODE REVIEW

**Review by robertpietzcker — APPROVED** [review]
Hi Chris, thanks a lot for doing the systematic check that all the cost data are the same after the refactoring! 
Could you add the path where the runs are to the PR? so that if ever a question comes up, people can simply go to these files (e.g. testOneRegi_SSP1_dev_2024-02-27_16.29.42/compare_refac.put) and check?

**Comment by robertpietzcker** [comment]
you did also check the learning parameters, right - so that all of `pm_data` is unchanged?

**Comment by cchrisgong** [comment]
@robertpietzcker yes, I checked learning paramters just now for all SSPs

**Comment by robertpietzcker** [comment]
thanks!

**Pull request merged**
