### PR TITLE
Add variable efficiencies for Electrolyzers

### PR DESCRIPTION
**Pull request by Loisel**
Adjust `elh2` in a time-dependent way, according to a PSI literature review: efficiency is 0.57 for 2010 and 0.73 for 2050, with a linear adjustment in-between. I then set 0.75 for 2055 onwards.

The values will also be part of the following publication:
Electricity storage and hydrogen: Technologies, costs and environmental burden, Christian Bauer (ed.), Thomas Heck, Simon Schneider, Harshil Desai Sanjaykumar, Tom Terlouw, Karin Treyer, Xiaojin Zhang, 2021.

### CODE REVIEW

**Comment by Loisel** [comment]
Of course, endogenous learning would be best for this important technology.

**Comment by robertpietzcker** [comment]
> Of course, endogenous learning would be best for this important technology.

it IS an endogenous learning technology already.
 I think Felix implemented that some months ago.

**Comment by Loisel** [comment]
> > Of course, endogenous learning would be best for this important technology.
> 
> it IS an endogenous learning technology already.
> I think Felix implemented that some months ago.

I was referring to learning which improves efficiencies, sorry for not being clear. Afaik REMIND learning only reduces costs (?).

**Review by fschreyer — APPROVED** [review]
Thanks for this, Alois! Of course, coupling the efficiency to the endogenous learning of capital cost would be the best long-term solution but this already helps.

**Pull request merged**
