### PR TITLE
restrict temporal extent of industry equations

### PR DESCRIPTION
**Pull request by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q**
- [x] Refactoring

## Checklist:

- [x] My code follows the [coding etiquette](https://github.com/remindmodel/remind/blob/develop/main.gms#L80)
- [ ] I performed a self-review of my own code
- [x] I explained my changes within the PR, particularly in hard-to-understand areas
- [x] I checked that the [in-code documentation](https://github.com/remindmodel/remind/blob/develop/main.gms#L120) is up-to-date
- [x] I adjusted the reporting in [`remind2`](https://github.com/pik-piam/remind2) where it was needed
- [x] I adjusted `forbiddenColumnNames` in [readCheckScenarioConfig.R](https://github.com/remindmodel/remind/blob/develop/scripts/start/readCheckScenarioConfig.R) in case the PR leads to deprecated switches
- [x] All automated model tests pass (`FAIL 0` in the output of `make test`)
- [x] The changelog `CHANGELOG.md` [has been updated correctly](https://gitlab.pik-potsdam.de/rse/rsewiki/-/wikis/Standards-for-Writing-a-Changelog)

### CODE REVIEW

**Review by Renato-Rodrigues — APPROVED** [review]
If you define a equation in `t`, I don't think you need the `t.val ge cm_startyear` as `t` should be already defined as that on the sets definition, no?

https://github.com/remindmodel/remind/blob/c55d667a2754c93da8d993c37551d0a691841f42/core/sets.gms#L1095

Besides that, thk you very much for the quick work on that!

**Comment by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q** [comment]
Let's do spring cleaning then. :tulip:

**Review by Renato-Rodrigues — APPROVED** [review]
It looks fine by me, as long as it works in a run.

**Comment by JakobBD** [comment]
Damn it, shout out to @cchrisgong who did this a while ago in the pbs branch and I undid it because I thought there was a purpose for this.

Have you tested reporting and cs2? I vaguely remember some issues popping up there, but I may be mistaken again.

**Comment by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q** [comment]
> Have you tested reporting and cs2? I vaguely remember some issues popping up there, but I may be mistaken again.

Only if for some reason the scripts access the flow equations outside of `t` …

**Pull request merged**
