### PR TITLE
improve readability of p_actualbudgetco2 for cm_iterative_target_adj 9

### PR DESCRIPTION
**Pull request by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q**
- [x] Refactoring

## Checklist:

- [x] My code follows the [coding etiquette](https://github.com/remindmodel/remind/blob/develop/main.gms#L80)
- [ ] I performed a self-review of my own code
- [x] I explained my changes within the PR, particularly in hard-to-understand areas
- [x] I checked that the [in-code documentation](https://github.com/remindmodel/remind/blob/develop/main.gms#L120) is up-to-date
- [x] I adjusted the reporting in [`remind2`](https://github.com/pik-piam/remind2) where it was needed
- [x] I adjusted `forbiddenColumnNames` in [readCheckScenarioConfig.R](https://github.com/remindmodel/remind/blob/develop/scripts/start/readCheckScenarioConfig.R) in case the PR leads to deprecated switches
- [ ] All automated model tests pass (`FAIL 0` in the output of `make test`)
- [x] The changelog `CHANGELOG.md` [has been updated correctly](https://gitlab.pik-potsdam.de/rse/rsewiki/-/wikis/Standards-for-Writing-a-Changelog)

### CODE REVIEW

**Comment by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q** [comment]
@katarkow, as I see it the "plus half a year" calculation only works correctly for five-year periods (i.e. until 2055).  The periods 2060 and 2070 (and further on) are 7.5 and 10 years long (2058–2064.5 and 2064.5–2074.5), respectively.  So this formulation adds up 4.25 and 5.5 years in those periods.
Not sure whether we care about a 5 % error for one period of the budget.

**Comment by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q** [comment]
Bump @robertpietzcker, @katarkow.

**Comment by katarkow** [comment]
Hi! Thanks for checking the calculations! Let's see:
- For 2060: years 2023-2057 (2057 included) are handled in `!! entire middle periods` and then we get `(pm_ttot_val(ttot) - pm_ttot_val(ttot-1)) / 2 + 0.5` which is 5/2 + 0.5, so the missing 3 years.
- For 2070, we cover 2023-2064.5 in `!! entire middle periods`, and the `(pm_ttot_val(ttot) - pm_ttot_val(ttot-1)) / 2 + 0.5` is 5.5 years so we also include 2070. Similarly for 2080, 2090, and 2100.

Or am I missing something?

**Comment by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q** [comment]
> Hi! Thanks for checking the calculations! Let's see:
> 
>     * For 2060: years 2023-2057 (2057 included) are handled in `!! entire middle periods` and then we get `(pm_ttot_val(ttot) - pm_ttot_val(ttot-1)) / 2 + 0.5` which is 5/2 + 0.5, so the missing 3 years.
> 
>     * For 2070, we cover 2023-2064.5 in `!! entire middle periods`, and the `(pm_ttot_val(ttot) - pm_ttot_val(ttot-1)) / 2 + 0.5` is 5.5 years so we also include 2070. Similarly for 2080, 2090, and 2100.
> 
> 
> Or am I missing something?

Yeah, makes sense.

I hate variable time steps …

**Review by robertpietzcker — APPROVED** [review]

**Pull request merged**
