### PR TITLE
fix negative fossil chemical emissions

### PR DESCRIPTION
**Pull request by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q**
close https://github.com/remindmodel/development_issues/issues/266

### CODE REVIEW

**Comment by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q** [comment]
`/p/tmp/pehl/Remind_twin/output/SSP2EU-NPi_2024-03-27_17.33.46`

**Comment by mellamoSimon** [comment]
thank you! let me know if it works :)

**Comment by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q** [comment]
Works.
image

**Comment by mellamoSimon** [comment]
great, thank you!

**Pull request merged**
