### PR TITLE
adds optional MAgPIE section to cs2 via cs2 profiles

### PR DESCRIPTION
**Pull request by chroetz**
# Purpose of this PR

Adds MAgPIE variables to compareScenarios2 in case of coupled runs.

When calling compareScenarios2 via output.R, it is now possible to choose `MAgPIE`  and `REMIND-MAgPIE`, for a cs2-report of certain MAgPIE variables (either only the MAgPIE-section or the whole default REMIND report with the MAgPIE-section at the end).

## Type of change

- [X] New feature 

## Checklist:

- [X] My code follows the coding etiquette
- [X] I have performed a self-review of my own code
- [X] Changes are commented, particularly in hard-to-understand areas
- [X] I have updated the in-code documentation
- [X] I have adjusted reporting where it was needed
- [X] The model compiles and runs successfully (`Rscript start.R -q`)

## Examples:
Here: `/p/tmp/cschoetz/cs2magpie/remind/`.
I took some runs from `/p/projects/remind/users/lmerfort/Navigate_industry/cpl_runs_2022_07_29/remind/output` and copied them in the output folder of the folder above. Then I ran `Rscript output.R` -> `Comparison across runs` -> `compareScenarios2` -> *chose some scenarios* -> *choose prefix Test or LMD* -> *choose slurm* -> `REMIND-MAgPIE` and `MAgPIE`. The results are the `compScen-*.pdf` files.

### CODE REVIEW

**Comment by gabriel-abrahao** [comment]
@chroetz I tested it by copying some month-old run folders/files in `/p/projects/piam/abrahao/scratch/cs2magpie/remind` , but apparently it couldn't find the MAgPIE variables and generated a PDF with all plots missing (see `/home/abrahao/projects_abrahao/scratch/cs2magpie/remind/compScen-2022-07-26_18.36.01-H12-MAgPIE.pdf` ). From  the associated `.out`, it never read the coupled `.mif`, just the ones inside the `-rem-5` folders, so it's not supposed to find these variables anyway. 

Is cs2 supposed to read the coupled mifs? Or is this supposed to work only with new runs with the proposed change of putting the coupled mif insisde the REMIND folder? If that's the case, maybe @orichters has some runs we could use to test. 

I'm not very familiar with the cs2 structure, let me know how can I help debuggin this. Either way, feel free to test things in that folder.

**Comment by chroetz** [comment]
Thanks @gabriel-abrahao ! 
I didn't change which mif-file is read, i.e., cs2 still only reads `output/<folder_of_run>/REMIND_generic_...mif`. If I see that correctly, after #908, these REMIND mif files will contain the MAgPIE variables. 
For testing in your folder, I copied the common mif files in  `output` to `output/<folder_of_run>` and renamed them `REMIND_generic_...mif`. A soon as the compute nodes are running again, we can test with that setup.

**Comment by chroetz** [comment]
Frist results to look at:
* `/p/projects/piam/abrahao/scratch/cs2magpie/remind/compScen-blub-2022-07-27_09.08.36-H12-MAgPIE.pdf` (only MAgPIE section)
* `/p/projects/piam/abrahao/scratch/cs2magpie/remind/compScen-blub-2022-07-27_09.08.36-H12-REMIND-MAgPIE.pdf` (REMIND + MAgPIE)

Please let me know, in case you like to have any changes, other plots, further variables, ...

**Comment by orichters** [comment]
> If I see that correctly, after #908, these REMIND mif files will contain the MAgPIE variables.

Indeed, older runs don't contain MAgPIE data so they will not work with the setting as it is.

**Review by gabriel-abrahao — APPROVED** [review]
Seems good to me, and the merge conflict looks trivial.

**Pull request merged**
