### PR TITLE
enable management of local calibration results

### PR DESCRIPTION
**Pull request by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q**
For production runs it is generally advisable to calibrate first, since establishing what exactly went into a given calibration results is an inherently manual process that is not guaranteed to yield definitive results.
This merge request adds a `set-local-calibration` target to the Makefile that implements [this tutorial](https://gitlab.pik-potsdam.de/pehl/tuts/-/blob/master/Using_local_REMIND_calibrations.md) (with some improvements).
Users will get a `calibration_results/` directory with a `collect_calibration` script that can be used to create `.tgz` files from calibration results (just like at `/p/projects/remind/inputdata/CESparametersAndGDX/`) and will have the directory included as a `remind_repos` option in their R session.  Use of local calibration results in REMIND from there on is identical to that of provided calibration results – simply set the `CESandGDXversion` accordingly.

- [x] New feature 

## Checklist:

- [x] My code follows the [coding etiquette](https://github.com/remindmodel/remind/blob/develop/main.gms#L80)
- [ ] I performed a self-review of my own code
- [x] I explained my changes within the PR, particularly in hard-to-understand areas
- [x] I checked that the [in-code documentation](https://github.com/remindmodel/remind/blob/develop/main.gms#L120) is up-to-date
- [x] I adjusted the reporting in [`remind2`](https://github.com/pik-piam/remind2) where it was needed
- [x] I adjusted `forbiddenColumnNames` in [readCheckScenarioConfig.R](https://github.com/remindmodel/remind/blob/develop/scripts/start/readCheckScenarioConfig.R) in case the PR leads to deprecated switches
- [x] All automated model tests pass (`FAIL 0` in the output of `make test`)
- [x] The changelog `CHANGELOG.md` [has been updated correctly](https://gitlab.pik-potsdam.de/rse/rsewiki/-/wikis/Standards-for-Writing-a-Changelog)

### CODE REVIEW

**Comment by fbenke-pik** [comment]
I don't think I have enough experience with REMIND and calibration to review this PR, so I'll leave this one to @LaviniaBaumstark

**Comment by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q** [comment]
Bump @LaviniaBaumstark.

**Review by fbenke-pik — CHANGES_REQUESTED** [review]
Tested this on the cluster and works for me. 

However, this option should be documented as well.
Maybe documentation should be a section of the [calibration tutorial of REMIND](https://github.com/remindmodel/remind/blob/develop/tutorials/12_Calibrating_CES_Parameters.md)?

**Comment by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q** [comment]
Should I just merge https://gitlab.pik-potsdam.de/REMIND/wiki/-/wikis/Handling-of-Gdx-and-Ces-Parameter-Files-in-Remind into the tutorial?  Bit silly to have it somewhere separate when the information is in the scripts included in the repository …

**Comment by LaviniaBaumstark** [comment]
yes, please, for external users we anyway will adjsut all tutorials

**Comment by fbenke-pik** [comment]
Right, from my understanding this is what needs to be done: This gitlab tutorial (currently not accessible from outside of PIK) should be moved to the official tutorial on github, even if external users won't be able to complete all the steps yet. We will then probably have to adapt them as part out our efforts to make REMIND usable for external users.

**Pull request merged**
