### PR TITLE
update income brackets for carbon price differentiation

### PR DESCRIPTION
**Pull request by nicobauer**
## Type of change

(Make sure to delete from the Type-of-change list the items not relevant to your PR)

- [ ] Bug fix 
- [ ] Refactoring
- [ ] New feature 
- [x ] Minor change (default scenarios show only small differences)
- [ ] Fundamental change
- [ ] This change requires a documentation update

## Checklist:

- [x ] My code follows the [coding etiquette](https://github.com/remindmodel/remind/blob/develop/main.gms#L80)
- [x ] I performed a self-review of my own code
- [x ] I explained my changes within the PR, particularly in hard-to-understand areas
- [ ] I checked that the [in-code documentation](https://github.com/remindmodel/remind/blob/develop/main.gms#L120) is up-to-date
- [ ] I adjusted the reporting in [`remind2`](https://github.com/pik-piam/remind2) where it was needed
- [ ] I adjusted `forbiddenColumnNames` in [readCheckScenarioConfig.R](https://github.com/remindmodel/remind/blob/develop/scripts/start/readCheckScenarioConfig.R) in case the PR leads to deprecated switches
- [x ] All automated model tests pass (`FAIL 0` in the output of `make test`)

## Further information (optional):

* Test runs are here: 
* Comparison of results (what changes by this PR?):

### CODE REVIEW

**Comment by nicobauer** [comment]
Once more!

**Review by strefler — APPROVED** [review]

**Comment by nicobauer** [comment]
Lavinia, I thought that already happened. Thus, Yes can be merged.

**Comment by LaviniaBaumstark** [comment]
you now first need to solve the problems of codeCheck. Usually the person generating the PR also merges after all checks have passed and you have at least one approval.

**Comment by LaviniaBaumstark** [comment]
do you plan to solve the conflicts and merge thsi PR?

**Comment by nicobauer** [comment]
This issue has been solved in a different pull-request by Laurin. You can close it and abandon it.

**Pull request closed without merging**
