### PR TITLE
stop on missing input files, without trying to unpack them

### PR DESCRIPTION
**Pull request by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q**
See pik-piam/gms#40

- [x] New feature 

## Checklist:

- [x] My code follows the coding etiquette
- [x] I have adjusted reporting where it was needed
- [x] The model compiles and runs successfully (`Rscript start.R -q`)

### CODE REVIEW

**Review by mikapfl — APPROVED** [review]

**Comment by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q** [comment]
> The dependency on the new `gms` will not be resolved automatically, people have to run `Rscript scripts/utils/updateRenv.R` or something similar to get it, if they don't and try to start a run, they'll just get an error.

If the package is updated on the machine (automatic on the cluster, and who besides me runs REMIND locally?), `./scripts/start/submit.R` will at least come nagging:
```
The new run will use the package environment defined in renv.lock, but it is out of sync, probably because you installed packages/updates manually. Write current package environment into renv.lock first? (Y/n)
```

**Comment by mikapfl** [comment]
By default, there are no automatic updates on the cluster, it just says for me currently:

```
The following PIK packages can be updated:
- edgeTransport : 0.21.0 -> 0.21.1
- gms : 0.20.0 -> 0.22.0
- lucode2 : 0.30.8 -> 0.31.0
- magclass : 6.5.2 -> 6.6.0
- magpie4 : 1.162.3 -> 1.164.0
- mrcommons : 1.22.7 -> 1.23.1
- mrmagpie : 1.28.10 -> 1.28.11
- mrvalidation : 2.40.6 -> 2.41.0
- mrwater : 1.3.9 -> 1.3.12
- remind2 : 1.103.5 -> 1.103.6
Consider updating with `Rscript scripts/utils/updateRenv.R`.
```

**Comment by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q** [comment]
Uhhh, that was disabled?

**Comment by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q** [comment]
No, wasn't:
```
$ version gms

Package: gms 
Installed version: 0.22.0 
Last updated: 41 minutes ago
```

But REMIND behaves differently on the cluster and locally.  Still, tells everybody what to do …

**Comment by mikapfl** [comment]
But… in the remind renv?

Because in my remind renv, it is 0.20 still:

```
15:30:07 ⌂5.08 [pflueger@login02:/p/tmp/pflueger/remind] develop(+83/-22)+* ± R

R version 4.1.2 (2021-11-01) -- "Bird Hippie"
[…]
Global .Rprofile loaded! (R version 4.1.2 (2021-11-01))
* Project '/p/tmp/pflueger/remind' loaded. [renv 0.16.0]

> packageVersion("gms")
[1] '0.20.0'
> 
```

**Comment by mikapfl** [comment]
And my testOneRegi fails (when forcing new input data):

```
2022-10-20 12:01:31: acquiring model lock...
acquired model lock in 0 secs.
Your input data are outdated or in a different regional resolution. New data are downloaded and distributed.
Error in `download_distribute()`:
! unused argument (stopOnMissing = TRUE)
Backtrace:
    x
 1. \-global prepare()
2022-10-20 12:01:35: unlocked model.
Execution halted
```

**Comment by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q** [comment]
Mine was nagging me to update, [see above](https://github.com/remindmodel/remind/pull/1024#issuecomment-1285230692).

**Comment by mikapfl** [comment]
Okay. I at least also get the warning that things are not the latest and greatest.
Well, anyway, adding the `checkDeps` from the upcoming lucode2 should be even better, to tell people when minimum requirements are not met.

**Pull request merged**
